USE [master]
GO

/****** Object:  Database [Estudiantes]    Script Date: 1/26/2020 9:44:22 PM ******/
CREATE DATABASE [Estudiantes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Estudiantes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estudiantes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Estudiantes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estudiantes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Estudiantes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Estudiantes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Estudiantes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Estudiantes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Estudiantes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Estudiantes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Estudiantes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Estudiantes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Estudiantes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Estudiantes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Estudiantes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Estudiantes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Estudiantes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Estudiantes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Estudiantes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Estudiantes] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Estudiantes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Estudiantes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Estudiantes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Estudiantes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Estudiantes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Estudiantes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Estudiantes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Estudiantes] SET RECOVERY FULL 
GO

ALTER DATABASE [Estudiantes] SET  MULTI_USER 
GO

ALTER DATABASE [Estudiantes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Estudiantes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Estudiantes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Estudiantes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Estudiantes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Estudiantes] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Estudiantes] SET  READ_WRITE 
GO

